version: 2

jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/xcode-install
    steps:
      - checkout

      - run:
          name: Update gem
          command: gem update --system

      - run:
          name: Install ruby dependencies
          command: bundle install

      - run:
          name: Run test
          command: bundle exec rake spec

      - run:
          name: Run lint
          command: bundle exec rake rubocop
